function gameType(props: gameTypeProps): GameTypeEnum {
  return props;
}

const GameType = {
  Galgame: gameType({
    name: 'Galgame',
    list: '/gameLists',
    label: 'galgame',
    webComment: '/getliuyan',
    update: '/updatagame',
    random: '/randgame',
    topGame: '/topgame',
    details: '/details',
    downloadType: 'game',
    detailComment: '/gamebook',
    search: '/so',
    vip: false,
  }),
  KrKr: gameType({
    name: 'KrKr',
    list: '/krkrGameLists',
    label: 'krkr',
    webComment: '/krkrGetliuyan',
    update: '/krkrUpdatagame',
    random: '/krkrRandgame',
    topGame: '/krkrTopgame',
    details: '/krkrDetails',
    downloadType: 'krkr',
    detailComment: '/krkrGamebook',
    search: '/krkrSo',
    vip: false,
  }),
  RPG: gameType({
    name: 'RPG',
    list: '/rpgGameLists',
    label: 'rpg',
    webComment: '/rpgGetliuyan',
    update: '/rpgUpdatagame',
    random: '/rpgRandgame',
    topGame: '/rpgTopgame',
    details: '/rpgDetails',
    downloadType: 'sstm',
    detailComment: '/rpgGamebook',
    search: '/rpgSo',
    vip: false,
  }),
  VR: gameType({
    name: '福利',
    list: '/vrLists',
    label: '3d',
    webComment: '/vrGetliuyan',
    update: '/vrUpdatagame',
    random: '/vrRandgame',
    topGame: '/vrTopgame',
    details: '/vrDetails',
    downloadType: 'vr',
    detailComment: 'vrGamebook',
    search: '/vrSo',
    vip: true,
  }),
  EX: gameType({
    name: '本子',
    list: '/exLists',
    label: 'ex',
    webComment: '/exGetliuyan',
    update: '/exUpdatagame',
    random: '/exRandgame',
    topGame: '/exTopgame',
    details: '/exDetails',
    downloadType: 'ex',
    detailComment: '/exGamebook',
    search: '/exSo',
    vip: true,
  }),
  Book: gameType({
    name: '轻小说',
    list: '/bookLists',
    label: 'book',
    webComment: '/bookGetliuyan',
    update: '/bookUpdatagame',
    random: '/bookRandgame',
    topGame: '/bookTopgame',
    details: '/bookDetails',
    downloadType: 'book',
    detailComment: '/bookGamebook',
    search: '/bookSo',
    vip: true,
  }),
} as const;

export default GameType;
